server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: loan-service-group
        auto-offset: reset=earliest
        key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: com.developerbank.cards.event
              use:
                type:
                  headers: false   # 🔥 To ignore package, i am using different package for cards and loan service
              value:
                default:
                  type: com.developerbank.cards.event.LoanRequestEvent
