services:
  accounts:
    image: "developerbank/accounts:p1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devbank
  loans:
    image: "developerbank/loans:p1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devbank
  cards:
    image: "developerbank/cards:p1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - devbank
networks:
  devbank:
    driver: "bridge"